bulletin_index:
    path:     /
    defaults: { _controller: "PMMLaboBundle:Bulletin:index" }
    methods:  GET

bulletin_show:
    path:     /{id}/show
    defaults: { _controller: "PMMLaboBundle:Bulletin:show" }
    methods:  GET

bulletin_new:
    path:     /new
    defaults: { _controller: "PMMLaboBundle:Bulletin:new" }
    methods:  [GET, POST]
    
bulletin_custum-new:
    path:     /{id}/new
    defaults: { _controller: "PMMLaboBundle:Bulletin:custumNew" }
    methods:  [GET, POST]

bulletin_edit:
    path:     /{id}/edit
    defaults: { _controller: "PMMLaboBundle:Bulletin:edit" }
    methods:  [GET, POST]

bulletin_delete:
    path:     /{id}/delete
    defaults: { _controller: "PMMLaboBundle:Bulletin:delete" }
    methods:  DELETE

bulletin_fill:
    path:     /{id}/fill
    defaults: { _controller: "PMMLaboBundle:Bulletin:fill" }
    methods:  [GET, POST]
    
bulletin_print:
    path:     /{id}/print
    defaults: { _controller: "PMMLaboBundle:Bulletin:print" }
    methods:  GET